# Generated by Django 5.0.6 on 2024-07-08 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_api_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('location_country', models.CharField(max_length=100)),
                ('location_city', models.CharField(max_length=100)),
                ('location_meta', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOT_PLATFORM.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(max_length=100)),
                ('sensor_category', models.CharField(max_length=100)),
                ('sensor_meta', models.CharField(max_length=100)),
                ('sensor_api_key', models.CharField(max_length=100)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOT_PLATFORM.location')),
            ],
        ),
    ]
