# Generated by Django 5.0.6 on 2024-07-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT_PLATFORM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_data', models.CharField(max_length=100)),
                ('sensor_data_time', models.DateTimeField(auto_now_add=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOT_PLATFORM.sensor')),
            ],
        ),
    ]
