# Generated by Django 5.0.6 on 2024-07-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT_PLATFORM', '0002_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_api_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_api_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
